name: 'Label Sync'
description: 'Synchronizes labels from a file to a GitHub Repository.'
author: 'DrBarnabus'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path labels configuration file'
    default: '.github/label-sync.yml'
    required: false
  owner:
    description: 'The owner of the target repository'
    required: true
  repo:
    description: 'The name of the target repository'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'